"""
서울 러닝 코스 데이터
- 각 코스별 기상청 격자 좌표(nx, ny), 카카오맵 좌표, 코스 정보 포함
- 기상청 격자 좌표는 기상청 공식 격자 변환 테이블 기준
"""

RUNNING_COURSES = {
    "🏠 홈코스 (옥수 기반)": [
        {
            "id": "oksusu_01",
            "name": "옥수-응봉산 코스",
            "description": "옥수역에서 출발해 응봉산을 거쳐 돌아오는 업힐 코스. 한강 전망이 일품입니다.",
            "distance_km": 5.0,
            "difficulty": "⭐⭐",
            "terrain": "포장+흙길",
            "start_location": "옥수역 2번 출구",
            "highlights": ["응봉산 팔각정 전망", "한강 야경"],
            "nx": 61,
            "ny": 126,
            "kakao_lat": 37.5425,
            "kakao_lng": 127.0158,
            "kakao_map_url": "https://map.kakao.com/?map_type=TYPE_MAP&itemId=&q=%EC%98%A5%EC%88%98%EC%97%AD&wx=127.0158&wy=37.5425&zoom=4",
        },
        {
            "id": "oksusu_02",
            "name": "옥수-한강 코스",
            "description": "옥수역에서 한강 변을 따라 반포까지 달리는 평지 코스. 초보자에게도 추천.",
            "distance_km": 8.0,
            "difficulty": "⭐",
            "terrain": "포장",
            "start_location": "옥수역 3번 출구",
            "highlights": ["한강 뷰", "달빛무지개분수"],
            "nx": 61,
            "ny": 126,
            "kakao_lat": 37.5425,
            "kakao_lng": 127.0158,
            "kakao_map_url": "https://map.kakao.com/?map_type=TYPE_MAP&itemId=&q=%EC%98%A5%EC%88%98%EC%97%AD&wx=127.0158&wy=37.5425&zoom=4",
        },
        {
            "id": "oksusu_03",
            "name": "옥수-성수-서울숲 코스",
            "description": "옥수에서 성수동 감성 거리를 지나 서울숲까지 이어지는 도심 투어 코스.",
            "distance_km": 7.0,
            "difficulty": "⭐",
            "terrain": "포장",
            "start_location": "옥수역 1번 출구",
            "highlights": ["성수동 카페거리", "서울숲"],
            "nx": 61,
            "ny": 127,
            "kakao_lat": 37.5448,
            "kakao_lng": 127.0442,
            "kakao_map_url": "https://map.kakao.com/?map_type=TYPE_MAP&itemId=&q=%EC%84%9C%EC%9A%B8%EC%88%B2&wx=127.0442&wy=37.5448&zoom=4",
        },
    ],
    "📍 서울 전체 코스": [
        {
            "id": "hangang_01",
            "name": "반포 한강 순환",
            "description": "잠수교를 포함한 순환 코스. 달빛무지개분수와 세빛섬이 포인트.",
            "distance_km": 6.0,
            "difficulty": "⭐",
            "terrain": "포장",
            "start_location": "반포한강공원",
            "highlights": ["달빛무지개분수", "세빛섬", "야경"],
            "nx": 59,
            "ny": 125,
            "kakao_lat": 37.5089,
            "kakao_lng": 126.9994,
            "kakao_map_url": "https://map.kakao.com/?map_type=TYPE_MAP&itemId=&q=%EB%B0%98%ED%8F%AC%ED%95%9C%EA%B0%95%EA%B3%B5%EC%9B%90&wx=126.9994&wy=37.5089&zoom=4",
        },
        {
            "id": "hangang_02",
            "name": "여의도 한강 순환",
            "description": "바닥이 평탄하고 폭이 넓어 초보자에게 최적. 여의도 선착장~샛강 생태공원 코스.",
            "distance_km": 7.0,
            "difficulty": "⭐",
            "terrain": "포장",
            "start_location": "여의도한강공원",
            "highlights": ["여의도 스카이라인", "샛강 생태공원"],
            "nx": 58,
            "ny": 126,
            "kakao_lat": 37.5285,
            "kakao_lng": 126.9327,
            "kakao_map_url": "https://map.kakao.com/?map_type=TYPE_MAP&itemId=&q=%EC%97%AC%EC%9D%98%EB%8F%84%ED%95%9C%EA%B0%95%EA%B3%B5%EC%9B%90&wx=126.9327&wy=37.5285&zoom=4",
        },
        {
            "id": "hangang_03",
            "name": "뚝섬 한강 롱런",
            "description": "잠실철교를 건너 강남으로 넘어가거나 강변을 따라 길게 달리기 좋은 중상급 코스.",
            "distance_km": 10.0,
            "difficulty": "⭐⭐",
            "terrain": "포장",
            "start_location": "뚝섬한강공원",
            "highlights": ["뚝섬 유원지", "한강 롱뷰"],
            "nx": 62,
            "ny": 126,
            "kakao_lat": 37.5296,
            "kakao_lng": 127.0687,
            "kakao_map_url": "https://map.kakao.com/?map_type=TYPE_MAP&itemId=&q=%EB%9A%9D%EC%84%AC%ED%95%9C%EA%B0%95%EA%B3%B5%EC%9B%90&wx=127.0687&wy=37.5296&zoom=4",
        },
        {
            "id": "hangang_04",
            "name": "잠실 롱런 코스",
            "description": "잠실한강공원에서 출발해 잠실대교를 왕복하는 풀코스 준비 코스.",
            "distance_km": 12.0,
            "difficulty": "⭐⭐",
            "terrain": "포장",
            "start_location": "잠실한강공원",
            "highlights": ["롯데타워 뷰", "잠실대교"],
            "nx": 63,
            "ny": 126,
            "kakao_lat": 37.5138,
            "kakao_lng": 127.0935,
            "kakao_map_url": "https://map.kakao.com/?map_type=TYPE_MAP&itemId=&q=%EC%9E%A0%EC%8B%A4%ED%95%9C%EA%B0%95%EA%B3%B5%EC%9B%90&wx=127.0935&wy=37.5138&zoom=4",
        },
        {
            "id": "olympic_01",
            "name": "올림픽공원 호반길",
            "description": "평탄한 호수 둘레길을 따라 달리는 초보자 추천 코스.",
            "distance_km": 3.5,
            "difficulty": "⭐",
            "terrain": "포장+흙길",
            "start_location": "올림픽공원 평화의 문",
            "highlights": ["호수 전망", "초보자 최적"],
            "nx": 63,
            "ny": 125,
            "kakao_lat": 37.5215,
            "kakao_lng": 127.1226,
            "kakao_map_url": "https://map.kakao.com/?map_type=TYPE_MAP&itemId=&q=%EC%98%AC%EB%A6%BC%ED%94%BD%EA%B3%B5%EC%9B%90&wx=127.1226&wy=37.5215&zoom=4",
        },
        {
            "id": "olympic_02",
            "name": "올림픽공원 전체 순환",
            "description": "공원 주요 명소를 두루 거치는 적당한 난이도 코스.",
            "distance_km": 5.0,
            "difficulty": "⭐",
            "terrain": "포장+흙길",
            "start_location": "올림픽공원 평화의 문",
            "highlights": ["9경 감상", "잔디밭"],
            "nx": 63,
            "ny": 125,
            "kakao_lat": 37.5215,
            "kakao_lng": 127.1226,
            "kakao_map_url": "https://map.kakao.com/?map_type=TYPE_MAP&itemId=&q=%EC%98%AC%EB%A6%BC%ED%94%BD%EA%B3%B5%EC%9B%90&wx=127.1226&wy=37.5215&zoom=4",
        },
        {
            "id": "namsan_01",
            "name": "남산 북측순환로",
            "description": "차량 통행이 제한된 안전한 코스. 완만한 업다운으로 심폐 강화 최적.",
            "distance_km": 6.7,
            "difficulty": "⭐⭐⭐",
            "terrain": "포장",
            "start_location": "남산 남측 주차장",
            "highlights": ["업힐 훈련", "서울 시내 전망"],
            "nx": 60,
            "ny": 125,
            "kakao_lat": 37.5512,
            "kakao_lng": 126.9882,
            "kakao_map_url": "https://map.kakao.com/?map_type=TYPE_MAP&itemId=&q=%EB%82%A8%EC%82%B0%EA%B3%B5%EC%9B%90&wx=126.9882&wy=37.5512&zoom=4",
        },
        {
            "id": "namsan_02",
            "name": "남산 전체 순환",
            "description": "북측+남측순환로를 연계하여 남산타워까지 오르는 도전적인 코스.",
            "distance_km": 10.0,
            "difficulty": "⭐⭐⭐",
            "terrain": "포장+흙길",
            "start_location": "남산 남측 주차장",
            "highlights": ["남산타워", "360도 서울 전망"],
            "nx": 60,
            "ny": 125,
            "kakao_lat": 37.5512,
            "kakao_lng": 126.9882,
            "kakao_map_url": "https://map.kakao.com/?map_type=TYPE_MAP&itemId=&q=%EB%82%A8%EC%82%B0%EA%B3%B5%EC%9B%90&wx=126.9882&wy=37.5512&zoom=4",
        },
        {
            "id": "bukhansan_01",
            "name": "북한산 둘레길 1코스",
            "description": "소나무숲길을 따라 달리는 자연 트레일. 초급자 트레일 러닝 입문 코스.",
            "distance_km": 5.0,
            "difficulty": "⭐⭐",
            "terrain": "흙길",
            "start_location": "북한산 탐방안내소",
            "highlights": ["소나무 숲", "자연 트레일"],
            "nx": 59,
            "ny": 129,
            "kakao_lat": 37.6389,
            "kakao_lng": 126.9757,
            "kakao_map_url": "https://map.kakao.com/?map_type=TYPE_MAP&itemId=&q=%EB%B6%81%ED%95%9C%EC%82%B0%EB%91%98%EB%A0%88%EA%B8%B8&wx=126.9757&wy=37.6389&zoom=4",
        },
        {
            "id": "bukhansan_02",
            "name": "북한산성 코스",
            "description": "오르막과 내리막이 반복되는 중급자 코스. 성곽길과 숲길을 동시에.",
            "distance_km": 8.0,
            "difficulty": "⭐⭐⭐",
            "terrain": "흙길+바위",
            "start_location": "북한산성 입구",
            "highlights": ["북한산성", "숲길"],
            "nx": 58,
            "ny": 129,
            "kakao_lat": 37.6508,
            "kakao_lng": 126.9638,
            "kakao_map_url": "https://map.kakao.com/?map_type=TYPE_MAP&itemId=&q=%EB%B6%81%ED%95%9C%EC%82%B0%EC%84%B1&wx=126.9638&wy=37.6508&zoom=4",
        },
        {
            "id": "cheonggyecheon",
            "name": "청계천 코스",
            "description": "도심 속 힐링 코스. 청계광장에서 시작해 청계천변을 따라 달리는 평지 코스.",
            "distance_km": 8.0,
            "difficulty": "⭐",
            "terrain": "포장",
            "start_location": "청계광장",
            "highlights": ["야경", "도심 속 자연"],
            "nx": 60,
            "ny": 127,
            "kakao_lat": 37.5697,
            "kakao_lng": 126.9766,
            "kakao_map_url": "https://map.kakao.com/?map_type=TYPE_MAP&itemId=&q=%EC%B2%AD%EA%B3%84%EA%B4%91%EC%9E%A5&wx=126.9766&wy=37.5697&zoom=4",
        },
        {
            "id": "seoul_forest",
            "name": "서울숲 코스",
            "description": "도심 속 대형 공원의 다양한 길. 잔디밭과 숲길이 어우러진 힐링 코스.",
            "distance_km": 4.0,
            "difficulty": "⭐",
            "terrain": "포장+잔디",
            "start_location": "서울숲 정문",
            "highlights": ["사슴 방사장", "메타세쿼이아 길"],
            "nx": 62,
            "ny": 126,
            "kakao_lat": 37.5448,
            "kakao_lng": 127.0442,
            "kakao_map_url": "https://map.kakao.com/?map_type=TYPE_MAP&itemId=&q=%EC%84%9C%EC%9A%B8%EC%88%B2&wx=127.0442&wy=37.5448&zoom=4",
        },
        {
            "id": "gwanghwamun",
            "name": "광화문-경복궁 코스",
            "description": "역사와 문화의 중심부를 달리는 특별한 경험. 광화문광장에서 청와대까지.",
            "distance_km": 5.0,
            "difficulty": "⭐⭐",
            "terrain": "포장",
            "start_location": "광화문광장",
            "highlights": ["경복궁", "청와대", "인왕산 뷰"],
            "nx": 60,
            "ny": 127,
            "kakao_lat": 37.5759,
            "kakao_lng": 126.9769,
            "kakao_map_url": "https://map.kakao.com/?map_type=TYPE_MAP&itemId=&q=%EA%B4%91%ED%99%94%EB%AC%B8%EA%B4%91%EC%9E%A5&wx=126.9769&wy=37.5759&zoom=4",
        },
        {
            "id": "bugaksan",
            "name": "북악산 트레일",
            "description": "서울 사대문 안을 감싸는 성곽길 트레일. 청운대에서 바라보는 서울 전망이 압도적.",
            "distance_km": 6.0,
            "difficulty": "⭐⭐⭐",
            "terrain": "흙길+돌계단",
            "start_location": "창의문(자하문)",
            "highlights": ["북악스카이웨이", "성곽길", "서울 전망"],
            "nx": 60,
            "ny": 127,
            "kakao_lat": 37.5927,
            "kakao_lng": 126.9649,
            "kakao_map_url": "https://map.kakao.com/?map_type=TYPE_MAP&itemId=&q=%EB%B6%81%EC%95%85%EC%82%B0&wx=126.9649&wy=37.5927&zoom=4",
        },
    ],
}

# 전체 코스 리스트 (flat)
def get_all_courses():
    all_courses = []
    for group, courses in RUNNING_COURSES.items():
        for course in courses:
            course["group"] = group
            all_courses.append(course)
    return all_courses


def get_course_by_id(course_id: str):
    for courses in RUNNING_COURSES.values():
        for course in courses:
            if course["id"] == course_id:
                return course
    return None
